### ISSUE TITLE
 Undefined index: args

### ISSUE THREAD

**Issue by tami5** [jenshaase/phel-lang#105]
Hay, exicited to explore this language. I've followed the instruction on setup page and got error  Undefined index: args` it just won't work

then I tried the repl with  `(defun create-a-string [string] (print (concat 'Printing: ' string)))`
```
>>> (defun create-a-string [string] (print (concat 'Printing: ' string)))
Phel\Exceptions\PhelCodeException: Can not resolve symbol defun
in /home/tamibam/code/php/phel/hello/vendor/phel/phel/src/php/Exceptions/PhelCodeException.php:18 (gen: /home/tamibam/code/php/phel/hello/vendor/phel/phel/src/php/Exceptions/PhelCodeException.php:18)

PHP Notice:  Undefined index: args in /home/tamibam/code/php/phel/hello/vendor/phel/phel/src/php/Exceptions/TextExceptionPrinter.php on
line 108
TypeError: Argument 1 passed to Phel\Exceptions\TextExceptionPrinter::buildPhpArgsString() must be of the type array, null given, called in /home/tamibam/code/php/phel/hello/vendor/phel/phel/src/php/Exceptions/TextExceptionPrinter.php on line 108
in /home/tamibam/code/php/phel/hello/vendor/phel/phel/src/php/Exceptions/TextExceptionPrinter.php:148 (gen: /home/tamibam/code/php/phel/hello/vendor/phel/phel/src/php/Exceptions/TextExceptionPrinter.php:148)

PHP Notice:  Undefined index: args in /home/tamibam/code/php/phel/hello/vendor/phel/phel/src/php/Exceptions/TextExceptionPrinter.php on
line 108
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Phel\Exceptions\TextExceptionPrinter::buildPhpArgsString() must be of the type array, null given, called in /home/tamibam/code/php/phel/hello/vendor/phel/phel/src/php/Exceptions/TextExceptionPrinter.php on line 108 and defined in /home/tamibam/code/php/phel/hello/vendor/phel/phel/src/php/Exceptions/TextExceptionPrinter.php:148
Stack trace:
#0 /home/tamibam/code/php/phel/hello/vendor/phel/phel/src/php/Exceptions/TextExceptionPrinter.php(108): Phel\Exceptions\TextExceptionPrinter->buildPhpArgsString()
#1 /home/tamibam/code/php/phel/hello/vendor/phel/phel/src/php/Runtime.php(108): Phel\Exceptions\TextExceptionPrinter->printStackTrace()
#2 [internal function]: Phel\Runtime->exceptionHandler()
#3 {main}
  thrown in /home/tamibam/code/php/phel/hello/vendor/phel/phel/src/php/Exceptions/TextExceptionPrinter.php on line 148

```

**Comment by tami5** [comment]
Wow Thats really interesting. Thanks a lot

**Comment by jenshaase** [comment]
Hi @tami5,

would you like to give me some Feedback regarding Phel? What did you like, what didn't you like?

Best regards,
Jens

**Comment by tami5** [comment]
Hay, thanks so much for for this awesome pace of software. Unfortunately, I no longer intend to continue developing with php ecosystem , however, will definitely use phel for future projects that requires php. Thanks 🙏
