### ISSUE TITLE
Cannot run simple hello-world

### ISSUE THREAD

**Issue by bentxt** [jenshaase/phel-lang#116]
Hi,
Still working with the tutorial and getting a new problem. All the run commands fail

```
vendor/bin/phel run src/boot.phel
# or
vendor/bin/phel run hello-world\\boot
# or
vendor/bin/phel run "hello-world\boot"
```

```
vendor/bin/phel run "hello-world\boot"
RuntimeException: Cannot load namespace: hello-world\boot
in ...phel/hello-world/vendor/phel/phel/src/php/Commands/RunCommand.php:38 (gen: .../phel/hello-world/vendor/phel/phel/src/php/Commands/RunCommand.php:38)

#0 .../phel/hello-world/vendor/phel/phel/src/php/Main.php(105): Phel\Commands\RunCommand->run('/Users/ben/usrd...', 'hello-world\boo...')
#1 ...phel/hello-world/vendor/phel/phel/src/php/Main.php(81): Phel\Main->executeRunCommand()
#2 .../phel/hello-world/vendor/phel/phel/src/php/Main.php(129): Phel\Main->run()
#3 .../phel/hello-world/vendor/phel/phel/phel(5): require_once('/Users/ben/usrd...')
```

Here my composer.json

cat composer.json
```
{
    "name": "ben/hello-world",
    "type": "project",
    "authors": [
        {
            "name": "Ben Srctxt",
            "email": "ben@srctxt.com"
        }
    ],
    "require": {
        "phel/phel": "dev-master"
    },
    "extra": {
      "phel": {
         "loader": {
            "hello-world\\": "src/"
         }
      }
   },
    "minimum-stability": "dev"
}
```

**Comment by jenshaase** [comment]
I think you need to run `composer dump-autoload` first. Then it should be working.

**Comment by jenshaase** [comment]
Thanks for pointing this out. I updated the documentation on the website!

**Comment by jenshaase** [comment]
Hi,

is this issue solved? Can I help you with anything else?

Best regards,
Jens

**Comment by jenshaase** [comment]
I will close this now. If you still have questions, open this issue again or start a new issue.
