### ISSUE TITLE
Prevent REPL from being closed on Exception

### ISSUE THREAD

**Issue by mabasic** [jenshaase/phel-lang#187]
When I use REPL to test some code, I often type something which causes an Exception and it closes the REPL. Then I have to start it again and retype everything.

Is there a way to prevent Exceptions from closing REPL even if they are bugs in the repl. Something like a try catch at the top level.
I want to see the Exception, but I also want to continue doing what I was doing.

Example:

Try running this in the REPL:

```
(print (\readline_info "library_version"))
```

Your REPL session will end with this exception:

```
>>> (print (\readline_info "library_version"))
Error: Undefined constant 'readline_info'
in string:1 (gen: /tmp/__phelQDr0ao:4)

PHP Notice:  Undefined index: args in /home/mabasic/code/src/github.com/mabasic/phel-json/vendor/phel/phel/src/php/Exceptions/TextExceptionPrinter.php on line 108
Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9003 (through xdebug.client_host/xdebug.client_port) :-(
TypeError: Argument 1 passed to Phel\Exceptions\TextExceptionPrinter::buildPhpArgsString() must be of the type array, null given, called in /home/mabasic/code/src/github.com/mabasic/phel-json/vendor/phel/phel/src/php/Exceptions/TextExceptionPrinter.php on line 108
in /home/mabasic/code/src/github.com/mabasic/phel-json/vendor/phel/phel/src/php/Exceptions/TextExceptionPrinter.php:148 (gen: /home/mabasic/code/src/github.com/mabasic/phel-json/vendor/phel/phel/src/php/Exceptions/TextExceptionPrinter.php:148)

PHP Notice:  Undefined index: args in /home/mabasic/code/src/github.com/mabasic/phel-json/vendor/phel/phel/src/php/Exceptions/TextExceptionPrinter.php on line 108
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Phel\Exceptions\TextExceptionPrinter::buildPhpArgsString() must be of the type array, null given, called in /home/mabasic/code/src/github.com/mabasic/phel-json/vendor/phel/phel/src/php/Exceptions/TextExceptionPrinter.php on line 108 and defined in /home/mabasic/code/src/github.com/mabasic/phel-json/vendor/phel/phel/src/php/Exceptions/TextExceptionPrinter.php:148
Stack trace:
#0 /home/mabasic/code/src/github.com/mabasic/phel-json/vendor/phel/phel/src/php/Exceptions/TextExceptionPrinter.php(108): Phel\Exceptions\TextExceptionPrinter->buildPhpArgsString()
#1 /home/mabasic/code/src/github.com/mabasic/phel-json/vendor/phel/phel/src/php/Runtime/Runtime.php(77): Phel\Exceptions\TextExceptionPrinter->printStackTrace()
#2 [internal function]: Phel\Runtime\Runtime->exceptionHandler()
#3 {main}
  thrown in /home/mabasic/code/src/github.com/mabasic/phel-json/vendor/phel/phel/src/php/Exceptions/TextExceptionPrinter.php on line 148
mabasic@mabasic-cube:~/code/src/github.com/mabasic/phel-json$
```

**Comment by mabasic** [comment]
I've seen that PsySH has this functionality: https://psysh.org/

**Comment by Chemaclass** [comment]
Thanks for reporting this issue, @mabasic. I created a PR already with the fix :)
